# Generated by Django 2.1.7 on 2019-03-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
