# Generated by Django 2.1.7 on 2019-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_remove_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=5, max_length=1024),
            preserve_default=False,
        ),
    ]
