# Generated by Django 2.1.7 on 2019-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.CharField(default=1024, max_length=1024),
            preserve_default=False,
        ),
    ]
